import { useState } from 'react';
import { FileText, Download, Printer, GraduationCap, Building2, User, Calendar } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { AcademicRecord, Semester, GRADING_SCALE, getGradeColorClass } from '@/lib/grading';
import { StudentProfile } from '@/lib/storage';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';

interface TranscriptViewProps {
  record: AcademicRecord;
  profile: StudentProfile | null;
  onSaveProfile: (profile: StudentProfile) => void;
}

export const TranscriptView = ({ record, profile, onSaveProfile }: TranscriptViewProps) => {
  const [isEditingProfile, setIsEditingProfile] = useState(!profile);
  const [editedProfile, setEditedProfile] = useState<StudentProfile>(
    profile || {
      name: '',
      matricNumber: '',
      department: '',
      faculty: '',
      level: '',
      admissionYear: '',
    }
  );

  const handleSaveProfile = () => {
    if (!editedProfile.name || !editedProfile.matricNumber) {
      toast.error('Please enter at least your name and matric number');
      return;
    }
    onSaveProfile(editedProfile);
    setIsEditingProfile(false);
    toast.success('Profile saved');
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('REVEREND FATHER MOSES ORSHIO ADASU UNIVERSITY', 105, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('ACADEMIC TRANSCRIPT', 105, 28, { align: 'center' });
    
    // Student Info
    doc.setFontSize(10);
    let yPos = 40;
    
    if (profile) {
      doc.text(`Name: ${profile.name}`, 20, yPos);
      doc.text(`Matric No: ${profile.matricNumber}`, 120, yPos);
      yPos += 7;
      doc.text(`Department: ${profile.department || 'N/A'}`, 20, yPos);
      doc.text(`Faculty: ${profile.faculty || 'N/A'}`, 120, yPos);
      yPos += 7;
      doc.text(`Admission Year: ${profile.admissionYear || 'N/A'}`, 20, yPos);
      yPos += 10;
    }

    // Line separator
    doc.line(20, yPos, 190, yPos);
    yPos += 10;

    // Semesters
    record.semesters.forEach((semester) => {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFont('helvetica', 'bold');
      doc.text(`${semester.name} - ${semester.level} Level (${semester.session})`, 20, yPos);
      yPos += 7;

      // Table headers
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('Code', 20, yPos);
      doc.text('Title', 45, yPos);
      doc.text('CU', 120, yPos);
      doc.text('Score', 135, yPos);
      doc.text('Grade', 155, yPos);
      doc.text('GP', 170, yPos);
      doc.text('WGP', 182, yPos);
      yPos += 5;

      // Course rows
      doc.setFont('helvetica', 'normal');
      semester.courses.forEach((course) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(course.code, 20, yPos);
        doc.text(course.title.substring(0, 30), 45, yPos);
        doc.text(course.creditUnits.toString(), 120, yPos);
        doc.text(course.score.toString(), 135, yPos);
        doc.text(course.grade, 155, yPos);
        doc.text(course.gradePoint.toString(), 170, yPos);
        doc.text(course.weightedGradePoint.toString(), 182, yPos);
        yPos += 5;
      });

      // Semester summary
      yPos += 3;
      doc.setFont('helvetica', 'bold');
      doc.text(`TCR: ${semester.tcr}  |  TCE: ${semester.tce}  |  TWGP: ${semester.twgp}  |  GPA: ${semester.gpa.toFixed(2)}`, 20, yPos);
      yPos += 10;
    });

    // Overall summary
    yPos += 5;
    doc.line(20, yPos, 190, yPos);
    yPos += 8;
    doc.setFontSize(11);
    doc.text(`CUMULATIVE GRADE POINT AVERAGE (CGPA): ${record.cgpa.toFixed(2)}`, 20, yPos);
    yPos += 7;
    doc.text(`DEGREE CLASSIFICATION: ${record.degreeClass}`, 20, yPos);
    yPos += 7;
    doc.text(`TOTAL CREDIT UNITS EARNED: ${record.totalTCE} of ${record.totalTCR}`, 20, yPos);

    // Footer
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 285);
    doc.text('This is an unofficial transcript generated by RFMOAU CGPA Calculator', 105, 285, { align: 'center' });

    doc.save(`transcript_${profile?.matricNumber || 'student'}.pdf`);
    toast.success('PDF exported successfully');
  };

  const exportToExcel = () => {
    const workbook = XLSX.utils.book_new();

    // Summary sheet
    const summaryData = [
      ['REVEREND FATHER MOSES ORSHIO ADASU UNIVERSITY'],
      ['ACADEMIC TRANSCRIPT'],
      [''],
      ['Student Information'],
      ['Name', profile?.name || 'N/A'],
      ['Matric Number', profile?.matricNumber || 'N/A'],
      ['Department', profile?.department || 'N/A'],
      ['Faculty', profile?.faculty || 'N/A'],
      [''],
      ['Academic Summary'],
      ['CGPA', record.cgpa.toFixed(2)],
      ['Degree Class', record.degreeClass],
      ['Total Credits Registered', record.totalTCR],
      ['Total Credits Earned', record.totalTCE],
      ['Total Weighted Grade Point', record.totalTWGP],
    ];
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

    // Courses sheet
    const coursesData = [
      ['Semester', 'Level', 'Session', 'Course Code', 'Course Title', 'Credit Units', 'Score', 'Grade', 'Grade Point', 'WGP'],
    ];
    record.semesters.forEach((semester) => {
      semester.courses.forEach((course) => {
        coursesData.push([
          semester.name,
          semester.level,
          semester.session,
          course.code,
          course.title,
          course.creditUnits.toString(),
          course.score.toString(),
          course.grade,
          course.gradePoint.toString(),
          course.weightedGradePoint.toString(),
        ]);
      });
    });
    const coursesSheet = XLSX.utils.aoa_to_sheet(coursesData);
    XLSX.utils.book_append_sheet(workbook, coursesSheet, 'Courses');

    // Semester summary sheet
    const semesterData = [
      ['Semester', 'Level', 'Session', 'TCR', 'TCE', 'TWGP', 'GPA'],
    ];
    record.semesters.forEach((semester) => {
      semesterData.push([
        semester.name,
        semester.level,
        semester.session,
        semester.tcr.toString(),
        semester.tce.toString(),
        semester.twgp.toString(),
        semester.gpa.toFixed(2),
      ]);
    });
    const semesterSheet = XLSX.utils.aoa_to_sheet(semesterData);
    XLSX.utils.book_append_sheet(workbook, semesterSheet, 'Semester Summary');

    XLSX.writeFile(workbook, `transcript_${profile?.matricNumber || 'student'}.xlsx`);
    toast.success('Excel file exported successfully');
  };

  return (
    <div className="space-y-6">
      {/* Profile Section */}
      <div className="card-elevated p-6 animate-slide-up">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10">
              <User className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h3 className="text-lg font-semibold">Student Profile</h3>
              <p className="text-sm text-muted-foreground">
                Your information for the transcript
              </p>
            </div>
          </div>
          {!isEditingProfile && (
            <Button variant="outline" size="sm" onClick={() => setIsEditingProfile(true)}>
              Edit Profile
            </Button>
          )}
        </div>

        {isEditingProfile ? (
          <div className="grid sm:grid-cols-2 gap-4">
            <div>
              <Label>Full Name *</Label>
              <Input
                value={editedProfile.name}
                onChange={(e) => setEditedProfile({ ...editedProfile, name: e.target.value })}
                placeholder="Enter your full name"
                className="mt-1"
              />
            </div>
            <div>
              <Label>Matric Number *</Label>
              <Input
                value={editedProfile.matricNumber}
                onChange={(e) => setEditedProfile({ ...editedProfile, matricNumber: e.target.value })}
                placeholder="e.g., BSU/2020/123456"
                className="mt-1"
              />
            </div>
            <div>
              <Label>Department</Label>
              <Input
                value={editedProfile.department}
                onChange={(e) => setEditedProfile({ ...editedProfile, department: e.target.value })}
                placeholder="e.g., Computer Science"
                className="mt-1"
              />
            </div>
            <div>
              <Label>Faculty</Label>
              <Input
                value={editedProfile.faculty}
                onChange={(e) => setEditedProfile({ ...editedProfile, faculty: e.target.value })}
                placeholder="e.g., Science"
                className="mt-1"
              />
            </div>
            <div>
              <Label>Current Level</Label>
              <Input
                value={editedProfile.level}
                onChange={(e) => setEditedProfile({ ...editedProfile, level: e.target.value })}
                placeholder="e.g., 300"
                className="mt-1"
              />
            </div>
            <div>
              <Label>Admission Year</Label>
              <Input
                value={editedProfile.admissionYear}
                onChange={(e) => setEditedProfile({ ...editedProfile, admissionYear: e.target.value })}
                placeholder="e.g., 2020/2021"
                className="mt-1"
              />
            </div>
            <div className="sm:col-span-2 flex gap-2">
              <Button onClick={handleSaveProfile}>Save Profile</Button>
              {profile && (
                <Button variant="outline" onClick={() => setIsEditingProfile(false)}>
                  Cancel
                </Button>
              )}
            </div>
          </div>
        ) : profile ? (
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Full Name</p>
              <p className="font-medium">{profile.name}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Matric Number</p>
              <p className="font-medium">{profile.matricNumber}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Department</p>
              <p className="font-medium">{profile.department || 'Not specified'}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Faculty</p>
              <p className="font-medium">{profile.faculty || 'Not specified'}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Current Level</p>
              <p className="font-medium">{profile.level || 'Not specified'}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Admission Year</p>
              <p className="font-medium">{profile.admissionYear || 'Not specified'}</p>
            </div>
          </div>
        ) : null}
      </div>

      {/* Export Options */}
      <div className="card-elevated p-6 animate-slide-up" style={{ animationDelay: '100ms' }}>
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 rounded-lg bg-accent/10">
            <Download className="w-5 h-5 text-accent" />
          </div>
          <div>
            <h3 className="text-lg font-semibold">Export Transcript</h3>
            <p className="text-sm text-muted-foreground">
              Download your academic record
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-4">
          <Button onClick={exportToPDF} className="gap-2" disabled={record.semesters.length === 0}>
            <FileText className="w-4 h-4" />
            Export as PDF
          </Button>
          <Button onClick={exportToExcel} variant="outline" className="gap-2" disabled={record.semesters.length === 0}>
            <Download className="w-4 h-4" />
            Export as Excel
          </Button>
        </div>

        {record.semesters.length === 0 && (
          <p className="text-sm text-muted-foreground mt-3">
            Add courses to enable transcript export.
          </p>
        )}
      </div>

      {/* Transcript Preview */}
      <div className="card-elevated p-6 animate-slide-up" style={{ animationDelay: '200ms' }}>
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 rounded-lg bg-primary/10">
            <FileText className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h3 className="text-lg font-semibold">Transcript Preview</h3>
            <p className="text-sm text-muted-foreground">
              Preview of your academic transcript
            </p>
          </div>
        </div>

        {/* Transcript Content */}
        <div className="border rounded-lg p-6 bg-background">
          {/* Header */}
          <div className="text-center mb-6 pb-6 border-b">
            <div className="flex justify-center mb-3">
              <div className="w-16 h-16 rounded-full bg-primary flex items-center justify-center">
                <GraduationCap className="w-8 h-8 text-primary-foreground" />
              </div>
            </div>
            <h2 className="text-xl font-bold">REVEREND FATHER MOSES ORSHIO ADASU UNIVERSITY</h2>
            <p className="text-muted-foreground">Academic Transcript</p>
          </div>

          {/* Student Info */}
          {profile && (
            <div className="grid sm:grid-cols-2 gap-4 mb-6 pb-6 border-b">
              <div className="flex items-center gap-2">
                <User className="w-4 h-4 text-muted-foreground" />
                <span className="text-sm">
                  <span className="text-muted-foreground">Name:</span> {profile.name}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-sm">
                  <span className="text-muted-foreground">Matric No:</span> {profile.matricNumber}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Building2 className="w-4 h-4 text-muted-foreground" />
                <span className="text-sm">
                  <span className="text-muted-foreground">Department:</span> {profile.department || 'N/A'}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-sm">
                  <span className="text-muted-foreground">Faculty:</span> {profile.faculty || 'N/A'}
                </span>
              </div>
            </div>
          )}

          {/* Semesters */}
          {record.semesters.length > 0 ? (
            <div className="space-y-6">
              {record.semesters.map((semester) => (
                <div key={semester.id} className="border rounded-lg overflow-hidden">
                  <div className="bg-muted px-4 py-2 flex items-center justify-between">
                    <span className="font-semibold">
                      {semester.name} - {semester.level} Level
                    </span>
                    <span className="text-sm text-muted-foreground">{semester.session}</span>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b bg-muted/50">
                          <th className="text-left p-3">Code</th>
                          <th className="text-left p-3">Title</th>
                          <th className="text-center p-3">CU</th>
                          <th className="text-center p-3">Score</th>
                          <th className="text-center p-3">Grade</th>
                          <th className="text-center p-3">GP</th>
                          <th className="text-center p-3">WGP</th>
                        </tr>
                      </thead>
                      <tbody>
                        {semester.courses.map((course) => (
                          <tr key={course.id} className="border-b">
                            <td className="p-3 font-medium">{course.code}</td>
                            <td className="p-3">{course.title}</td>
                            <td className="p-3 text-center">{course.creditUnits}</td>
                            <td className="p-3 text-center">{course.score}</td>
                            <td className="p-3 text-center">
                              <span className={cn('grade-badge', getGradeColorClass(course.grade))}>
                                {course.grade}
                              </span>
                            </td>
                            <td className="p-3 text-center">{course.gradePoint}</td>
                            <td className="p-3 text-center">{course.weightedGradePoint}</td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot>
                        <tr className="bg-muted/30 font-medium">
                          <td colSpan={2} className="p-3">Semester Summary</td>
                          <td className="p-3 text-center" title="Total Credit Registered">
                            <span className="text-xs text-muted-foreground block">TCR</span>
                            {semester.tcr}
                          </td>
                          <td className="p-3 text-center" title="Total Credit Earned">
                            <span className="text-xs text-muted-foreground block">TCE</span>
                            {semester.tce}
                          </td>
                          <td colSpan={2} className="p-3 text-center" title="Total Weighted Grade Point">
                            <span className="text-xs text-muted-foreground block">TWGP</span>
                            {semester.twgp}
                          </td>
                          <td className="p-3 text-center text-accent font-bold" title="Grade Point Average">
                            <span className="text-xs text-muted-foreground block">GPA</span>
                            {semester.gpa.toFixed(2)}
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                </div>
              ))}

              {/* Overall Summary */}
              <div className="bg-primary text-primary-foreground rounded-lg p-6">
                <div className="grid sm:grid-cols-4 gap-4 text-center">
                  <div>
                    <p className="text-primary-foreground/70 text-sm">CGPA</p>
                    <p className="text-3xl font-bold">{record.cgpa.toFixed(2)}</p>
                  </div>
                  <div>
                    <p className="text-primary-foreground/70 text-sm">Degree Class</p>
                    <p className="text-lg font-semibold">{record.degreeClass}</p>
                  </div>
                  <div>
                    <p className="text-primary-foreground/70 text-sm">Total TCR</p>
                    <p className="text-2xl font-bold">{record.totalTCR}</p>
                  </div>
                  <div>
                    <p className="text-primary-foreground/70 text-sm">Total TCE</p>
                    <p className="text-2xl font-bold">{record.totalTCE}</p>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="text-center py-12">
              <FileText className="w-12 h-12 mx-auto mb-4 text-muted-foreground opacity-50" />
              <p className="text-muted-foreground">
                No academic records yet. Add semesters and courses to generate a transcript.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Grading Scale Reference */}
      <div className="card-elevated p-6 animate-slide-up" style={{ animationDelay: '300ms' }}>
        <h3 className="text-lg font-semibold mb-4">RFMOAU Grading Scale (5-Point System)</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
          {GRADING_SCALE.map((grade) => (
            <div
              key={grade.grade}
              className={cn(
                'p-4 rounded-lg text-center',
                getGradeColorClass(grade.grade)
              )}
            >
              <p className="text-2xl font-bold">{grade.grade}</p>
              <p className="text-sm">{grade.min} - {grade.max}%</p>
              <p className="text-xs mt-1">{grade.point} Points</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
